### ISSUE TITLE
Docstrings needed

### ISSUE THREAD

**Issue by BeebBenjamin** [bodleian/archiox-mirador-plugin#1]
The functions need documenting with docstrings so that people can understand how functions work and why they exist

**Comment by BeebBenjamin** [comment]
The helper strings have been documented.  Unsure if we should document the react classes, they don't do that in Mirador Image Tools @irv

**Comment by irv** [comment]
Nobody has ever complained that there's _too much_ documentation

**Comment by BeebBenjamin** [comment]
Good point, I have however complained about a lack of Miradro plug-in docs.

**Comment by BeebBenjamin** [comment]
Fixed.
